# Generated by Django 3.0.8 on 2020-07-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_login_method'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
