# Generated by Django 3.0.7 on 2020-06-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampedmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timestampedmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
