# Generated by Django 3.1 on 2020-08-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_custommodelmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModelManager',
        ),
    ]
